export const ITEM_IMAGES = {
  'ember_blade':'../assets/weapon/fire/ember_blade.png',
  'flame_dagger':'../assets/weapon/fire/flame_dagger.png',
  'inferno_sword':'../assets/weapon/fire/inferno_sword.png',
  'burning_staff':'../assets/weapon/fire/burning_staff.png',
  'ashen_tome':'../assets/weapon/fire/ashen_tome.png',
  'lava_gauntlets':'../assets/weapon/fire/lava_gauntlets.png',
  'tide_blade':'../assets/weapon/water/tide_blade.png',
  'ocean_staff':'../assets/weapon/water/ocean_staff.png',
  'flow_dagger':'../assets/weapon/water/flow_dagger.png',
  'deep_tome':'../assets/weapon/water/deep_tome.png',
  'current_gauntlets':'../assets/weapon/water/current_gauntlets.png',
  'stone_sword':'../assets/weapon/earth/stone_sword.png',
  'root_blade':'../assets/weapon/earth/root_blade.png',
  'titan_hammer':'../assets/weapon/earth/titan_hammer.png',
  'crystal_staff':'../assets/weapon/earth/crystal_staff.png',
  'boulder_gauntlets':'../assets/weapon/earth/boulder_gauntlets.png',
  'wind_dagger':'../assets/weapon/air/wind_dagger.png',
  'gale_blade':'../assets/weapon/air/gale_blade.png',
  'storm_sword':'../assets/weapon/air/storm_sword.png',
  'sky_staff':'../assets/weapon/air/sky_staff.png',
  'swift_gauntlets':'../assets/weapon/air/swift_gauntlets.png',
  'shadow_blade':'../assets/weapon/dark/shadow_blade.png',
  'void_dagger':'../assets/weapon/dark/void_dagger.png',
  'curse_sword':'../assets/weapon/dark/curse_sword.png',
  'nightmare_staff':'../assets/weapon/dark/nightmare_staff.png',
  'abyss_gauntlets':'../assets/weapon/dark/abyss_gauntlets.png',
  'radiant_blade':'../assets/weapon/light/radiant_blade.png',
  'halo_staff':'../assets/weapon/light/halo_staff.png',
  'dawn_sword':'../assets/weapon/light/dawn_sword.png',
  'blessing_tome':'../assets/weapon/light/blessing_tome.png',
  'light_gauntlets':'../assets/weapon/light/light_gauntlets.png',
  'cinder_armor':'../assets/armor/cinder_armor.png',
  'inferno_cloak':'../assets/armor/inferno_cloak.png',
  'blazing_robes':'../assets/armor/blazing_robes.png',
  'smoke_veil':'../assets/armor/smoke_veil.png',
  'mist_cloak':'../assets/armor/mist_cloak.png',
  'ocean_armor':'../assets/armor/ocean_armor.png',
  'rain_robes':'../assets/armor/rain_robes.png',
  'tide_shield':'../assets/armor/tide_shield.png',
  'rock_armor':'../assets/armor/rock_armor.png',
  'root_cloak':'../assets/armor/root_cloak.png',
  'terra_plate':'../assets/armor/terra_plate.png',
  'crystal_shell':'../assets/armor/crystal_shell.png',
  'feather_cloak':'../assets/armor/feather_cloak.png',
  'storm_armor':'../assets/armor/storm_armor.png',
  'cloud_robes':'../assets/armor/cloud_robes.png',
  'wind_veil':'../assets/armor/wind_veil.png',
  'shadow_cloak':'../assets/armor/shadow_cloak.png',
  'void_armor':'../assets/armor/void_armor.png',
  'nightmare_robes':'../assets/armor/nightmare_robes.png',
  'curse_shell':'../assets/armor/curse_shell.png',
  'holy_armor':'../assets/armor/holy_armor.png',
  'blessing_cloak':'../assets/armor/blessing_cloak.png',
  'radiant_robes':'../assets/armor/radiant_robes.png',
  'halo_shield':'../assets/armor/halo_shield.png',
  'rune_ignis':'../assets/runes/rune_ignis.png',
  'rune_aqua':'../assets/runes/rune_aqua.png',
  'rune_terra':'../assets/runes/rune_terra.png',
  'rune_aero':'../assets/runes/rune_aero.png',
  'rune_umbra':'../assets/runes/rune_umbra.png',
  'rune_lux':'../assets/runes/rune_lux.png',
  // Base helmets & shields
  'scrap_helm':     '../assets/armor/scrap_helm.png',
  'scrap_shield':   '../assets/armor/scrap_shield.png',
  'iron_helm':      '../assets/armor/iron_helm.png',
  'iron_shield':    '../assets/armor/iron_shield.png',
  'tactical_helm':  '../assets/armor/tactical_helm.png',
  'tactical_shield':'../assets/armor/tactical_shield.png',
  // Tactical weapon
  'iron_sword':     '../assets/weapon/iron_sword.png',
  'tactical_sword': '../assets/weapon/tactical_sword.png',
  // Watcher Set
  'watcher_eye_ring': '../assets/sets/watcher_eye_ring.png',
  'watcher_band':     '../assets/sets/watcher_band.png',
  'watcher_cloak':    '../assets/sets/watcher_cloak.png',
  'watcher_crown':    '../assets/sets/watcher_crown.png',
}
